[package]
name = "cfromr"
version = "0.1.0"
authors = ["Marat Zabirov <maratn566ek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake="0.1.44"
bindgen="0.55.1"